apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ include "drupal.fullname" . }}-pvc"
  labels:
    {{- include "drupal.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.pvc.storage_class }}
  resources:
    requests:
      storage: {{ .Values.pvc.storage_size }}
